### ISSUE TITLE
Probabilistic Image Colorization

### ISSUE THREAD

**Issue by RoyiAvital** [ameroyer/ameroyer.github.io#1]
Hi,

Will you upload a code for [Probabilistic Image Colorization](https://arxiv.org/abs/1705.04258)?

Thank You.

**Comment by ameroyer** [comment]
Hi,

Yes we plan to release the code on Github soon, I'll let you know when it's available

Best,
Amelie

**Comment by ameroyer** [comment]
Github link: https://github.com/ameroyer/PIC
